### ISSUE TITLE
I'm interested in what you guys are doing, when will it probably be made public?

### ISSUE THREAD

**Issue by gwt-ZJU** [BCV-Uniandes/STRIDE#1]
I'm interested in what you guys are doing, when will it probably be made public?

**Comment by nayobi** [comment]
Hello, we are still organizing our data and codes. The data will be uploaded this week. The code will be in the upcoming weeks.

**Comment by nayobi** [comment]
We have finally uploaded all our materials. Feel free to email me at n.ayobi@uniandes.edu.co if needed.

**Comment by nayobi** [comment]
We have finally uploaded all our materials. Feel free to email me at n.ayobi@uniandes.edu.co if needed.
